### ISSUE TITLE
When you move the token to the right of the grid, it doesn't place the token right

### ISSUE THREAD

**Issue by StefGeraets** [StefGeraets/battleroyale#3]
### Reproduce

Use arrow keys to move the token.
When moving to the last column the token moves to the wrong grid cell.

**Comment by PushpenderSaini0** [comment]
In function `makeGrid` you increment x before you place the appendChild element that will cause a wrong grid to be made .
You can fix this issue by moving the line
```js
game.el.container.appendChild(cell).className = "grid-item grid-item-" + x + "-" + y;
```
before the if condition .

You can assign the issue to me and i will soon submit a PR
